url: http://jrwalk.github.io
permalink: pretty
highlighter: pygments
markdown: kramdown
exclude: ['Gemfile', 'CNAME', 'README.markdown']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"