url: http://jrwalk.github.io
permalink: pretty
highlighter: rouge
markdown: kramdown
exclude: ['Gemfile', 'CNAME', 'README.markdown']
github: {
    "owner_name": "John Walk",
    "owner_url": "https://github.com/jrwalk",
    "language": null,
    "is_user_page": true,
    "is_project_page": false
}

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      subtitle: "John Walk"