version: "3.7"

services:
  jekyll-server:
    build:
      context: ./
    environment:
      BUNDLE_GEMFILE: /opt/app/Gemfile
    volumes:
      - .:/opt/app
    ports:
      - "4000:4000"
    command: bundle exec jekyll --watch
